name: "generate"
on:
    workflow_dispatch: ~
    schedule:
        -   cron: "0 8 * * 1" # At 08:00 on Monday

jobs:
    generate:
        name: "Generate Bots class"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "8.1"

                dependencies:
                    - "highest"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v3"

            -   name: "Setup PHP, with composer and extensions"
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php-version }}"
                    extensions: "${{ env.PHP_EXTENSIONS }}"
                    coverage: "none"

            -   name: "Install composer dependencies"
                uses: "ramsey/composer-install@v2"
                with:
                    dependency-versions: "${{ matrix.dependencies }}"

            -   name: "Generate Bots class"
                run: "php bin/generate-bots-class"

            -   name: "Create Pull Request"
                uses: "peter-evans/create-pull-request@v3"
